# .gitlab-ci.yml

# 定义 CI/CD 阶段
stages:
  - test

# 使用 Node.js 镜像
image: node:latest

# 缓存 node_modules 加速后续构建
cache:
  paths:
    - node_modules/

# 运行测试（Jest/Mocha）
run_tests:
  stage: test
  script:
    - echo "Running tests..."
    - pwd
    - node -v
    - node curl.js gitlink
  only:
    - main
# 构建项目（如前端项目需要 build）

