# 使用 Node.js 官方镜像
image: node:20

# 定义缓存（加速后续构建）
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/
        - build/

stages:
    - build

build-job: # This job runs in the build stage, which runs first.
    stage: build
    script:
        - echo "============================================================="
        - pwd
        - node curl.js
