version: '1.0'
name: test
displayName: test
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''

stages:
  - name: try
    displayName: node-pack
    strategy: naturally
    trigger: auto
    executor:
      - loveagri
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 20.10.0
        commands:
          - echo '--------------------------------'
          - pwd
          - node curl.js gitee
          - echo '--------------------------------'
        strategy:
          retry: '0'
